### ISSUE TITLE
دقیقا این خط بناست چه چیزی را بارگذ اری کند؟ چه پرونده‌ای نیاز است بارگذاری شود؟

### ISSUE THREAD

**Issue by yoosofan** [yoosofan/mano-computer-simulator-js#1]
https://github.com/yoosofan/mano-computer-simulator-js/blob/896aa0dda6b4b35aac8e90ea65ba89aace4ee4ff/index.html#L44

**Comment by yoosofan** [comment]
هنوز به این پاسخی ندادید

**Comment by ahmadi9721174201fateme** [comment]
سلام استاد ما برای دریافت داده های ram از کاربر این خط کد را نوشتیم تا داده ها را به صورت جدول در excel، بتواند در سایت ما بارگذاری کند و ما از ان داده ها استفاده کنیم . که شما گفتید به جای فایل excel از فایل جاوا اسکریپت استفاده کنیم و ما طبق پیشنهاد شما از  import استفاده کردیم اما برای آدرس دهی آن به مشکل برخوردیم که آن مشکل را همراه تیکه کد آن commit کرده ام.

**Comment by ahmadi9721174201fateme** [comment]
ببخشید استاد ما با این بخش از github  آشنا نبودیم دیر پیام شما را دیدیم

**Comment by yoosofan** [comment]
نوشتم که یک textarea بگذارید و کاربر خودش در آن در صورت نیاز کپی می‌کند و محتوای درون آن را به کار ببرید. نیازی به پرونده نیست

**Comment by ahmadi9721174201fateme** [comment]
بله ممنون استاد همین کار را می کنیم
